### ISSUE TITLE
Slowdown when movement key is held down, when terminal is large

### ISSUE THREAD

**Issue by Quantum-cross** [unblevable/quick-scope#8] opened 2015-08-04 18:17 UTC
Thank you for closing my other issue so quickly! I'm having another strange issue.

If my terminal is large (~78 lines tall), as I hold down any `hjkl` movement key, quick-scope will begin to slow down the cursor. With quick scope off, the cursor moves at a constant speed.

The first few lines will move at the normal speed, and since I would assume that quick-scope operates on a line by line basis, I would not expect it to slow down the farther I move.

To make this issue more strange, there is no problem if the terminal is smaller, say ~31 lines tall.

Let me know if there is any more information I can provide. Thanks!

**Comment by ghost** [comment] 2015-08-05 08:44
The plugin is a bit slow for me in general when moving lines. Might only be the case in larger files though.

Maybe use CursorHold instead of CursorMoved?

**Comment by szaghi** [comment] 2015-08-06 04:01
I am also sperimenting a boring slow movements when the plugin is enabled. This happens for files quite small (about 500 sloc) but only when lines are tall (132). Presently, I had to disable this plugin, that is in general wonderful!

Thank you very much for this great plugin!

**Comment by Quantum-cross** [comment] 2015-08-06 05:02
Yeah just wanted to say that as a new vim user, this extension is fantastic. I found counting line movements very strange and I never knew where my cursor would end up.

I'm glad someone else is able to reproduce this issue!

**Comment by Quantum-cross** [comment] 2015-08-06 22:46
For some reason I can't reproduce this issue at all today...

**Comment by unblevable** [comment] 2015-08-12 22:27
If anyone could include a GIF or screencast of this issue that'd be great.

**Comment by ruanyl** [comment] 2019-01-30 12:04
This happens to me as well, when moving by pressing `j/k`, it becomes slow and not smooth.

To solve the issue, I have to set `let g:qs_highlight_on_keys = ['f', 'F']`, to manually trigger highlight

**Comment by bradford-smith94** [comment] 2019-02-10 02:29
For those that do not want to use the `g:qs_highlight_on_keys` option, I have added an option (`g:qs_lazy_highlight`) which will change the `CursorMoved` event to be `CursorHold`. This should take care of any slowdown caused by highlighting. This issue will be closed when the change is merged into master, if someone can prove the slowdown still exists with the change then feel free to open a new issue.

**Closed as completed** 2019-02-10 03:12 UTC
