### ISSUE TITLE
Highlighting Stays On

### ISSUE THREAD

**Issue by ChiliConSql** [unblevable/quick-scope#72] opened 2021-02-15 20:21 UTC
Even though I set `let g:qs_highlight_on_keys = ['f', 'F', 't', 'T']` the highlighting is always on.

I am using Neovim v.0.4.4

**Comment by bradford-smith94** [comment] 2021-02-16 23:04
I installed Neovim (v0.4.4) and did not reproduce this.

I used the `init.vim` configuration of: 
```
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc
```
in order to run with [my Vim config](https://github.com/bradford-smith94/dotfiles/blob/master/vimrc) (which has the highlight on keys set in it - [line 108](https://github.com/bradford-smith94/dotfiles/blob/master/vimrc#L108)) as suggested by the [Neovim help](https://neovim.io/doc/user/nvim.html#nvim-from-vim).

My current guess is that it could be a configuration error or conflict with another plugin or setting, I suggest you try to determine the minimal configuration file that will reproduce the issue.

**Comment by ChiliConSql** [comment] 2021-02-18 05:50
@bradford-smith94 thank you for your input. 

It looks like the issue is "where" I put the directive. If I put it in nvimrc after initializing the plugin, it works. But if I put it in "plugins" folder, it doesn't, even though opening a file and issuing:
`:echo g:qs_highlight_on_keys` produces the correct result of `['f', 'F', 't', 'T']`.

Any idea why, and where can I place this directive outside of nvimrc/init.vim.?

**Comment by bradford-smith94** [comment] 2021-02-18 22:08
Sure, the why is most likely because of the order in which the vim/nvim configuration files are sourced. When the quick-scope plugin file is sourced is when it checks for the value of `g:qs_highlight_on_keys`, so if your settings file is sourced after that it will not matter what you set it to. This particular value isn't setup to be changed or toggled at runtime so it isn't checked anywhere else in the code, but that could be a possible enhancement.

The builtin help page `:help initialization` can provide more detail on the order that files are loaded, specifically the `:help load-plugins` section applies here, although the help page doesn't seem to provide much information on how the plugins are ordered themselves.

You can use the command `:scriptnames` to see the order in which vim/nvim has processed files, the goal here would be to get the file that contains the `g:qs_highlight_on_keys` setting to be loaded before `.../quick-scope/plugin/quick_scope.vim` (the `...` changes depending on where your plugins are installed). I'm not exactly sure how much you can do to force vim/nvim to load your file first, but it might be worth it to experiment with changing the name of the file (I would guess that some sort of alphabetical loading might take place, but my `:scriptnames` output doesn't seem to be ordered).

If nothing else works you can put the file in a place that vim/nvim will not automatically load (I like to use `~/.vim/custom/` for this purpose) and then explicitly `source` that file in your vimrc/init.vim so that it loads before vim/nvim move on to processing plugin files.

**Comment by gerazov** [comment] 2021-11-09 15:00
This should be in the README :wink:

**Comment by Nebell** [comment] 2024-02-27 08:41
In Neovim v0.9.5 with lazy.nvim, I solved the problem with the following config:
``` lua
{        
  "unblevable/quick-scope",
  event = "BufReadPost",
  init = function ()
    vim.g.qs_highlight_on_keys = { 'f', 'F' }
  end,
}
```
This may be able to help you. 😃

**Comment by bradford-smith94** [comment] 2024-07-05 15:57
Added a note to README, also see #98.

Closing this issue, as it is now linked in README so finding the relevant discussion should be possible.

**Closed as completed by bradford-smith94** 2024-07-05 15:57 UTC
