### ISSUE TITLE
Undefined variable s:chars_s

### ISSUE THREAD

**Issue by w2kpro** [unblevable/quick-scope#98] opened 2024-02-16 09:15 UTC
Vim 9.1 on Manjaro Linux (vim -f -u .vimrc-core)
quick-scope installed using Plug
Added "let g:qs_highlight_on_keys = ['f', 'F', 't', 'T']" to .vimrc-core
Characters are highlighted, but when cursor is moved to a new line the following error occurs:
Error detected while processing function quick_scope#HighlightLineDelayCallback[2]..quick_scope
#HighlightLine[12]..<SNR>49_get_highlight_patterns[130]..<SNR>49_save_chars_with_secondary_high
lights:
line    6:
E121: Undefined variable: s:chars_s

**Comment by vizcay** [comment] 2024-02-25 12:59
Exact same problem here with `NVIM v0.9.4` and 

```
  vim.cmd [[
    let g:qs_highlight_on_keys = ['f', 'F', 't', 'T']
    augroup qs_colors
      autocmd!
      autocmd ColorScheme * highlight QuickScopePrimary guifg='#afff5f' gui=underline ctermfg=155 cterm=underline
      autocmd ColorScheme * highlight QuickScopeSecondary guifg='#5fffff' gui=underline ctermfg=81 cterm=underline
    augroup END
  ]]
```

<img width="1278" alt="Screenshot 2024-02-25 at 16 58 23" src="https://github.com/unblevable/quick-scope/assets/4545990/4ffda3e6-a107-4048-8fad-31aa356e80ab">

**Comment by ktowen** [comment] 2024-06-13 14:35
Any solution for this?

**Comment by quolpr** [comment] 2024-06-19 14:55
Issue still present. Issue happens when `qs_highlight_on_keys` is set

**Comment by unblevable** [comment] 2024-06-30 21:00
I can't reproduce the error while running `NVIM v0.9.4` on `Ubuntu 22.04`. Can someone provide more context, possibly their `.vimrc`?

**Comment by ktowen** [comment] 2024-07-05 10:53
I'm able to reproduce it with this configuration. It only fails at the beginning of the lines at the end of the config

```
-- Install `lazy.nvim` plugin manager
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	local lazyrepo = "https://github.com/folke/lazy.nvim.git"
	vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
end ---@diagnostic disable-next-line: undefined-field
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
	{
		"unblevable/quick-scope",
		config = function()
			vim.g.qs_highlight_on_keys = { "f", "F", "t", "T" }
		end,
	},
})

-- NVIM v0.10.0
--------------------------------------
--- Next lines will give an error
--------------------------------------

--
-- export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
--
-- # zstyle ':omz:update' mode disabled  # disable automatic updates
--

```

**Comment by bradford-smith94** [comment] 2024-07-05 14:46
Thanks @ktowen, using this config I can reproduce (nvim v0.10.0 on Archlinux).

Interesting findings:
- when run with this config quick-scope appears to run as if `g:qs_highlight_on_keys` is not set
    - this can be verified by running `:autocmd CursorMoved` and seeing `call quick_scope#HighlightLineDelay(2, g:qs_accepted_chars)` registered
- running both vim and nvim (using my vimrc, no nvim specific config, except without setting `g:qs_highlight_on_keys`) does not reproduce the issue

I'm still trying to dig into the _why_ a bit more, but from this I can already tell that `g:qs_highlight_on_keys` (although it is being set) is not being set before quick-scope is initialized, which is something the plugin does not currently support.

This error has something to do with when `folke/lazy.nvim` is actually setting the variable. I haven't checked out that plugin yet, but I've confirmed this by moving the variable set line to outside of that lazy plugin and the error has disappeared (as well as quick-scope actually runs in `g:qs_highlight_on_keys` mode) -- i.e. - the following config does not cause the error:

```
-- Install `lazy.nvim` plugin manager
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	local lazyrepo = "https://github.com/folke/lazy.nvim.git"
	vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
end ---@diagnostic disable-next-line: undefined-field
vim.opt.rtp:prepend(lazypath)

vim.g.qs_highlight_on_keys = { "f", "F", "t", "T" }
require("lazy").setup({
	{
		"unblevable/quick-scope",
		config = function()
			vim.g.qs_highlight_on_keys = { "f", "F", "t", "T" }
		end,
	},
})

-- NVIM v0.10.0
--------------------------------------
--- Next lines will give an error
--------------------------------------

--
-- export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
--
-- # zstyle ':omz:update' mode disabled  # disable automatic updates
--

```

**Comment by bradford-smith94** [comment] 2024-07-05 15:37
Removed the "plugin-interactions" label, while the specific config I tested was caused by another plugin interaction this issue is more generally a timing issue caused by when `g:qs_highlight_on_keys` is set.

The latest update `v2.6.2` should avoid the errors by locking in the operating mode at plugin initialization. But there still exists a potential for miss-config where the user thinks they have set `g:qs_highlight_on_keys` (as above) but because of when the plugin is actually initialized vs when the variable is actually set quick-scope may not behave in "keys" highlighting mode.

**Comment by bradford-smith94** [comment] 2024-07-05 15:58
Added a note to README, also see #72.

Closing this issue, as it is now linked in README so finding the relevant discussion should be possible.

**Closed as completed by bradford-smith94** 2024-07-05 15:58 UTC

**Comment by josh-nz** [comment] 2024-07-19 08:00
You want to use the `init` function in the Lazy plugin manager spec for this plugin:

```lua
return {
  "unblevable/quick-scope",
  init = function()
    vim.g.qs_highlight_on_keys = { "f", "F", "t", "T" }
  end,
}
```

Ref: https://lazy.folke.io/spec
